# Generated by Django 5.0.2 on 2024-02-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_ka',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_ru',
        ),
    ]
