# Generated by Django 5.0.2 on 2024-02-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_remove_photo_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
