# Generated by Django 5.0.2 on 2024-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_photo_description_en_photo_description_ka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='header',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='header_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='header_ka',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='header_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
