# Generated by Django 5.0.2 on 2024-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='what_we_do',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='what_we_do',
            name='description_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='what_we_do',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='what_we_do',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='what_we_do',
            name='title_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='what_we_do',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
