# Generated by Django 5.0.2 on 2024-02-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangi',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hangi',
            name='content_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hangi',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hangi',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hangi',
            name='title_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hangi',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
