# Generated by Django 5.0.2 on 2024-02-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hangi_content_en_hangi_content_ka_hangi_content_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('header_en', models.CharField(max_length=100, null=True)),
                ('header_ru', models.CharField(max_length=100, null=True)),
                ('header_ka', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('content_ka', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.CharField(max_length=100)),
                ('headers_en', models.CharField(max_length=100, null=True)),
                ('headers_ru', models.CharField(max_length=100, null=True)),
                ('headers_ka', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('content_ka', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Hangi',
            new_name='About',
        ),
    ]
