# Generated by Django 5.0.2 on 2024-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_activities_mission_photo_rename_hangi_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=100)),
                ('home_en', models.CharField(max_length=100, null=True)),
                ('home_ru', models.CharField(max_length=100, null=True)),
                ('home_ka', models.CharField(max_length=100, null=True)),
                ('social', models.CharField(max_length=100)),
                ('social_en', models.CharField(max_length=100, null=True)),
                ('social_ru', models.CharField(max_length=100, null=True)),
                ('social_ka', models.CharField(max_length=100, null=True)),
                ('gallery', models.CharField(max_length=100)),
                ('gallery_en', models.CharField(max_length=100, null=True)),
                ('gallery_ru', models.CharField(max_length=100, null=True)),
                ('gallery_ka', models.CharField(max_length=100, null=True)),
                ('team', models.CharField(max_length=100)),
                ('team_en', models.CharField(max_length=100, null=True)),
                ('team_ru', models.CharField(max_length=100, null=True)),
                ('team_ka', models.CharField(max_length=100, null=True)),
                ('project', models.CharField(max_length=100)),
                ('project_en', models.CharField(max_length=100, null=True)),
                ('project_ru', models.CharField(max_length=100, null=True)),
                ('project_ka', models.CharField(max_length=100, null=True)),
                ('done', models.CharField(max_length=100)),
                ('done_en', models.CharField(max_length=100, null=True)),
                ('done_ru', models.CharField(max_length=100, null=True)),
                ('done_ka', models.CharField(max_length=100, null=True)),
                ('doing', models.CharField(max_length=100)),
                ('doing_en', models.CharField(max_length=100, null=True)),
                ('doing_ru', models.CharField(max_length=100, null=True)),
                ('doing_ka', models.CharField(max_length=100, null=True)),
                ('partnership', models.CharField(max_length=100)),
                ('partnership_en', models.CharField(max_length=100, null=True)),
                ('partnership_ru', models.CharField(max_length=100, null=True)),
                ('partnership_ka', models.CharField(max_length=100, null=True)),
                ('apps', models.CharField(max_length=100)),
                ('apps_en', models.CharField(max_length=100, null=True)),
                ('apps_ru', models.CharField(max_length=100, null=True)),
                ('apps_ka', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100)),
                ('contact_en', models.CharField(max_length=100, null=True)),
                ('contact_ru', models.CharField(max_length=100, null=True)),
                ('contact_ka', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
