# Generated by Django 5.0.2 on 2024-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='meniu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lists',
            name='meniu_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lists',
            name='meniu_ka',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lists',
            name='meniu_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
