# Generated by Django 5.0.2 on 2024-03-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lists_meniu_lists_meniu_en_lists_meniu_ka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('image_en', models.ImageField(null=True, upload_to='photos/')),
                ('image_ru', models.ImageField(null=True, upload_to='photos/')),
                ('image_ka', models.ImageField(null=True, upload_to='photos/')),
                ('city', models.CharField(max_length=100)),
                ('city_en', models.CharField(max_length=100, null=True)),
                ('city_ru', models.CharField(max_length=100, null=True)),
                ('city_ka', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('address_en', models.CharField(max_length=100, null=True)),
                ('address_ru', models.CharField(max_length=100, null=True)),
                ('address_ka', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('phone_en', models.CharField(max_length=100, null=True)),
                ('phone_ru', models.CharField(max_length=100, null=True)),
                ('phone_ka', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_en', models.EmailField(max_length=254, null=True)),
                ('email_ru', models.EmailField(max_length=254, null=True)),
                ('email_ka', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
