# Generated by Django 5.0.2 on 2024-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee_photos/')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_ka', models.CharField(max_length=100, null=True)),
                ('history', models.TextField()),
                ('history_en', models.TextField(null=True)),
                ('history_ru', models.TextField(null=True)),
                ('history_ka', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='group_photos/')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ka', models.TextField(null=True)),
            ],
        ),
    ]
