# Generated by Django 5.0.2 on 2024-03-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupphoto',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupphoto',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='groupphoto',
            name='description_ka',
        ),
        migrations.RemoveField(
            model_name='groupphoto',
            name='description_ru',
        ),
        migrations.AlterField(
            model_name='groupphoto',
            name='image',
            field=models.ImageField(upload_to='GroupPhotos'),
        ),
    ]
