# Generated by Django 5.0.2 on 2024-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0003_remove_groupphoto_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupphoto',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='groupphoto',
            name='image',
            field=models.ImageField(upload_to='group_photos/'),
        ),
    ]
