# Generated by Django 5.0.2 on 2024-02-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phartner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
