# Generated by Django 5.0.2 on 2024-03-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('header_en', models.CharField(max_length=100, null=True)),
                ('header_ru', models.CharField(max_length=100, null=True)),
                ('header_ka', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
